databases:
  - name: spamguard-db
    plan: free  # free, starter, standard, pro
    region: frankfurt

services:
  - type: web
    name: spamguard-api
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: spamguard-db
          property: connectionString
      - key: FRONTEND_URL
        sync: false  # A configurer manuellement avec ton URL Netlify
